version: '3'
services:
  app:
    build: .
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    command: npm start
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '0.7GB'

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - app
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.3GB'
